LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := png

LOCAL_C_INCLUDES := $(LOCAL_PATH)/include

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

LOCAL_SRC_FILES := \
	$(subst $(LOCAL_PATH)/,, \
	$(wildcard $(LOCAL_PATH)/*.c))

LOCAL_CFLAGS += -DGL_GLEXT_PROTOTYPES -DPNG_NO_ASSEMBLER_CODE
LOCAL_LDLIBS := -ldl -lGLESv1_CM -lGLESv2 -llog -landroid -lzlib
LOCAL_LDLIBS += $(LOCAL_PATH)/../../obj/local/$(TARGET_ARCH_ABI)

include $(BUILD_STATIC_LIBRARY)

